const base = import.meta.env.BASE_URL;

export const storefrontHeroSlides = [
  {
    id: 'apple-watch-ultra',
    eyebrow: 'Built for adventure',
    title: 'Apple Watch Ultra',
    subtitle: 'Strong, capable and ready for every day.',
    ctaLabel: 'Shop Apple Watch',
    href: './apple-watch.html',
    image: {
      src: `${base}hero/apple-watch-ultra.webp`,
      alt: 'Apple Watch Ultra with dark trail loop',
      width: 1179,
      height: 1172,
    },
    theme: 'warm',
    fit: 'contain',
  },
  {
    id: 'uncle-apple-store',
    eyebrow: 'The Gambia',
    title: 'Uncle Apple Store',
    subtitle: 'Original Apple devices, sourced with care.',
    ctaLabel: 'View Products',
    href: '#inventory',
    image: {
      src: `${base}hero/uncle-apple-store.webp`,
      alt: 'Uncle Apple Store showroom in The Gambia',
      width: 1500,
      height: 1000,
    },
    theme: 'photo',
    fit: 'cover',
  },
  {
    id: 'carefully-sourced',
    eyebrow: 'Sourced in Germany',
    title: 'Carefully picked',
    subtitle: 'We personally inspect devices before they reach The Gambia.',
    ctaLabel: 'Why Choose Us',
    href: './about/',
    image: {
      src: `${base}hero/carefully-sourced.webp`,
      alt: 'Uncle Apple Store carefully inspecting Apple products at a German electronics dealer',
      width: 1333,
      height: 1000,
    },
    theme: 'photo',
    fit: 'cover',
  },
  {
    id: 'iphone-16-purple',
    eyebrow: 'New colour',
    title: 'iPhone 16 Purple',
    subtitle: 'Beautiful colour. Powerful everyday performance.',
    ctaLabel: 'Shop iPhones',
    href: '#inventory',
    image: {
      src: `${base}hero/iphone-16-purple.webp`,
      alt: 'Purple iPhone 16 viewed from the back',
      width: 1179,
      height: 1178,
    },
    theme: 'purple',
    fit: 'contain',
  },
  {
    id: 'germany-to-gambia',
    eyebrow: '',
    title: 'Trusted Apple Devices from Germany',
    subtitle: '',
    ctaLabel: '',
    href: '#inventory',
    image: {
      src: `${base}hero/germany-gambia-clean.webp`,
      desktopSrc: `${base}hero/germany-gambia-clean-desktop.webp`,
      alt: 'Trusted Apple devices sourced in Germany and delivered to The Gambia',
      width: 1920,
      height: 1080,
    },
    theme: 'artwork',
    fit: 'contain',
  },
];
